apiVersion: v1
kind: Service
metadata:
  name: spring-boot-k8s-skaffold-demo
  labels:
    name: spring-boot-k8s-skaffold-demo
spec:
  ports:
    - nodePort: 30143 
      port: 7070
      targetPort: 7070
      protocol: TCP
  type: NodePort 
  selector:
    app: spring-boot-k8s-skaffold-demo